"""CSI-authenticated Quarto documents."""

from __future__ import annotations

import json
import os
from pathlib import Path

from shiny import reactive, req

from . import client, config
from .shiny import _get_current_session, server_wrapper


def quarto_setup(
    protected_body: str | Path = ".csiapps-protected-body.html",
    config_file: str | Path = ".csiapps-quarto.json",
    sandbox: bool | None = None,
) -> None:
    """Attach CSI authentication to a Quarto Shiny document.

    Call once from a normal Python cell in a Quarto document using the csiapps
    extension and ``server: shiny``. Quarto runs the cell again for each viewer;
    the call is a no-op during document rendering. Sandbox mode reveals the
    document locally without contacting CSI authentication.

    Args:
        protected_body: Private report-body file generated by the extension.
        config_file: Private runtime configuration generated by the extension.
        sandbox: Override the normal csiapps sandbox-mode resolution.
    """
    session = _get_current_session()
    if session is None:
        if os.environ.get("QUARTO_DOCUMENT_PATH"):
            return
        raise RuntimeError("quarto_setup() must be called from an active Shiny session")
    if sandbox is None:
        sandbox = config.is_sandbox_mode()
    body_path = Path(protected_body)
    config_path = Path(config_file)
    runtime_config = {}
    if config_path.is_file():
        runtime_config = json.loads(config_path.read_text(encoding="utf-8"))
        institute = runtime_config.get("institute")
        if institute:
            config.set_institute(institute)

    def initialize(input, output, session):
        initialized = reactive.value(False)

        @reactive.effect
        async def _initialize_quarto():
            if not sandbox:
                req(client.token_ready())
            req(not initialized())
            if not body_path.is_file():
                raise FileNotFoundError(f"Protected Quarto body not found: {body_path}")
            await session.send_custom_message(
                "csiapps_quarto_init",
                {
                    "body": body_path.read_text(encoding="utf-8"),
                    "title": runtime_config.get("title"),
                },
            )
            initialized.set(True)

    try:
        from shiny.express import input
    except ImportError as error:  # pragma: no cover - Shiny controls this module
        raise RuntimeError("quarto_setup() requires a Shiny Express document") from error

    server_wrapper(
        initialize,
        sandbox=sandbox,
        pause_on_logout=True,
    )(input, None, session)


__all__ = ["quarto_setup"]
