"""CSI-authenticated Quarto documents and offline snapshot data."""

from __future__ import annotations

import json
import math
import os
from collections.abc import Callable, Mapping
from datetime import date, datetime
from pathlib import Path
from typing import Any

import pandas as pd
from shiny import reactive, req

from . import client, config
from .shiny import _get_current_session, server_wrapper

_MAX_SAFE_INTEGER = 2**53 - 1


def _json_value(value: Any) -> Any:
    if value is None or value is pd.NA:
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, int):
        return str(value) if abs(value) > _MAX_SAFE_INTEGER else value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, Mapping):
        return {str(key): _json_value(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_value(item) for item in value]
    if hasattr(value, "item"):
        return _json_value(value.item())
    if isinstance(value, (str, int, float)):
        return value
    raise TypeError(f"unsupported snapshot value: {type(value).__name__}")


def _datasets_json(datasets: Mapping[str, Any]) -> str:
    if not isinstance(datasets, Mapping) or not datasets:
        if datasets == {}:
            return "{}"
        raise TypeError("snapshot_data() must return a mapping of named datasets")

    normalized = {}
    for name, dataset in datasets.items():
        if not isinstance(name, str) or not name:
            raise ValueError("snapshot dataset names must be non-empty strings")
        if isinstance(dataset, pd.DataFrame):
            records = dataset.to_dict(orient="records")
        elif isinstance(dataset, list) and all(isinstance(row, Mapping) for row in dataset):
            records = dataset
        else:
            raise TypeError(
                f"snapshot dataset {name!r} must be a pandas DataFrame or list of records"
            )
        normalized[name] = _json_value(records)

    return json.dumps(
        normalized,
        ensure_ascii=False,
        separators=(",", ":"),
        allow_nan=False,
    )


def quarto_setup(
    snapshot_data: Callable[[], Mapping[str, Any]] = lambda: {},
    protected_body: str | Path = ".csiapps-protected-body.html",
    config_file: str | Path = ".csiapps-quarto.json",
    sandbox: bool | None = None,
) -> None:
    """Attach CSI authentication and snapshot data to a Quarto Shiny document.

    Call once from a server-executed Python cell in a Quarto document using the
    csiapps extension and ``server: shiny``. The provider runs once per viewer,
    after authentication, and its result never enters process-global state.

    Args:
        snapshot_data: Zero-argument callable returning named pandas DataFrames
            or lists of record dictionaries.
        protected_body: Private report-body file generated by the extension.
        config_file: Private runtime configuration generated by the extension.
        sandbox: Override the normal csiapps sandbox-mode resolution.
    """
    if not callable(snapshot_data):
        raise TypeError("snapshot_data must be a zero-argument callable")
    session = _get_current_session()
    if session is None:
        if os.environ.get("QUARTO_DOCUMENT_PATH"):
            return
        raise RuntimeError("quarto_setup() must be called from an active Shiny session")
    if sandbox is None:
        sandbox = config.is_sandbox_mode()
    body_path = Path(protected_body)
    config_path = Path(config_file)
    runtime_config = {}
    if config_path.is_file():
        runtime_config = json.loads(config_path.read_text(encoding="utf-8"))
        institute = runtime_config.get("institute")
        if institute:
            config.set_institute(institute)

    def initialize(input, output, session):
        initialized = reactive.value(False)

        @reactive.effect
        async def _initialize_quarto():
            req(client.token_ready())
            req(not initialized())
            if not body_path.is_file():
                raise FileNotFoundError(f"Protected Quarto body not found: {body_path}")
            await session.send_custom_message(
                "csiapps_quarto_init",
                {
                    "body": body_path.read_text(encoding="utf-8"),
                    "datasets_json": _datasets_json(snapshot_data()),
                    "title": runtime_config.get("title"),
                },
            )
            initialized.set(True)

    try:
        from shiny.express import input
    except ImportError as error:  # pragma: no cover - Shiny controls this module
        raise RuntimeError("quarto_setup() requires a Shiny Express document") from error

    server_wrapper(initialize, sandbox=sandbox)(input, None, session)


__all__ = ["quarto_setup"]
